### ISSUE TITLE
Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "oauth-type" does not.

### ISSUE THREAD

**Issue by odera89** [yasudacloud/strapi-plugin-sso#11]
Strapi Version 4.4.0

After I installed this package to my strapi, I got this issue "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "oauth-type" does not." 

Can you guys help to find what exactly the problem?

https://capture.dropbox.com/kJHleEF83uNLQLG0

**Comment by yasudacloud** [comment]
@odera89 
Hello, thank you for getting back to us.

I see that you are using GraphQL.
It seems to me that the problem is caused by the use of hyphens in the plugin.

If you give us a little more time, we will try to find a solution here. 
In that case, you probably need to increase the version of the plugin.

**Comment by odera89** [comment]
Thank you for the fast reply, I will wait sure. You mean to upgrade my strapi to a higher version?

**Comment by yasudacloud** [comment]
@odera89 
No, I am considering modifying the plugin.
I am not familiar with Strapi's GraphQL as I have never used it, but at what point does this error occur?

**Comment by odera89** [comment]
1. installed this plugin with sso
2. added lines to the config plugins.js
3. npm run strapi develop and error, doesn't start the strapi. so when i want to run the strapi...

**Comment by yasudacloud** [comment]
Okay, I understand the situation.
Please give us 1-2 days to fix it.

**Comment by yasudacloud** [comment]
@odera89 
I had time to do it, so I fixed it now.
Could you please upgrade the plugin version and try it?
The latest version is 0.1.6

**Comment by odera89** [comment]
I had a bit time, and i checked. Thank you so much. It works very well. You have a beer :) I think you can close this ticket.
