### ISSUE TITLE
"openid" in the scopes of callback and 404

### ISSUE THREAD

**Issue by vojthor** [yasudacloud/strapi-plugin-sso#13]
Hey,
first of all, thanks a lot for the great plugin!

While integrating Strapi with our stack, my colleague ran into a problem when he tried to log in with his Google account and got a 404. I've tried to debug issue and I can see this in callback URL:
`&scope=email%20profile**%20openid%20**https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email` 
Rest of guys is not having this and me neither as well... Any idea what could be the cause of that?

Thanks a lot, 
Vojtech

**Comment by yasudacloud** [comment]
@vojthor 
Hi, I am honored that you used it.
Please take a few minutes to do some research. I will let you know something in the next few days at the latest.

By the way, do you run debugging with this command?
```shell
npm run build & npm run start
```

or this one?

```shell
npm run develop --watch-admin
```

**Comment by vojthor** [comment]
Hey, thanks for your reply!
I saw it running in prod mode (with npm run start), I really can't reproduce that URL with any of my accounts, it's just that one account my colleague is having for some reason...

**Comment by yasudacloud** [comment]
@vojthor 
I had a few thoughts.

We need to isolate if it is a Google account issue. Can you try to log in with another Google account in that person's running environment that doesn't work?

By the way, I thought openid was included in the callback even if you can log in successfully, but I was wrong?

Sorry for the trouble, but thank you.

**Comment by vojthor** [comment]
Sorry I got confused myself with that openid... it's even in working "flows" as you correctly mentioned... 
Two Google accounts were tried on that particular machine and both failed... 
The full URL that is triggering 404 on Strapi side is like that (just removed the code and domain)
`/strapi-plugin-sso/google/callback?code=XXX&scope=email%20profile%20https://www.googleapis.com/auth/userinfo.email%20https://www.googleapis.com/auth/userinfo.profile%20openid&authuser=1&hd=xxx.com&prompt=none`
I really can't see anything weird in there :(

**Comment by yasudacloud** [comment]
If you try to open "/strapi-plugin-sso/google/callback" from a browser without a query, you should get the following error and not a 404.
![スクリーンショット 2023-02-23 0 12 14](https://user-images.githubusercontent.com/44352732/220666230-c45b6ea3-0fc0-4dd4-b534-71be51d09155.png)


If you get a 404, then you may not be able to access Strapi properly from that machine.
For example, you may have rewritten the hosts to refer to a different environment, or if there is a web server in front, it may not be working properly.

**Comment by vojthor** [comment]
At this URL we were able to display the correct Auth failed screen on that computer. 
Unfortunately I don't have physical access to that computer, as it is several thousand miles away, it would be much easier for everyone... :D

**Comment by yasudacloud** [comment]
@vojthor 
I see, it seems difficult to determine the cause of the problem.
If the problem occurs only on that machine, how about trying a different browser or trying it in incognito mode?

By the way, if an error occurs inside the plugin, it should be output to the log.
https://github.com/yasudacloud/strapi-plugin-sso/blob/main/server/controllers/google.js#L114

**Comment by vojthor** [comment]
@yasudacloud thanks for the tip about the logs in the plugin, i was able to find request to Google (https://accounts.google.com/o/oauth2/token) ending with 400
and  `data: { error: 'invalid_grant', error_description: 'Bad Request' }"﻿`﻿ ...
After quick Googling it seems there could be s**tload  reasons for but I guess we can rule out it's plugin itself...

**Comment by vojthor** [comment]
@yasudacloud also multiple browsers were tested on that machine (Chrome, Safari, FF) and Chrome incognito with same results

**Comment by yasudacloud** [comment]
@vojthor 
Sorry for the late reply.
Have you made any progress since then?
I'm not very familiar with the GCP side of the setup, but let me know if I can help!

**Comment by vojthor** [comment]
No need to apologize at all, you doing me favor :) Nothing new yet, trying to figure what circumstance would Strapi make to output the URL that should be send to Google like this...
`const response = await httpClient.post(OAUTH_TOKEN_ENDPOINT, params, {
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded'
      }
    })`
![Untitled](https://user-images.githubusercontent.com/9679359/221231033-499df289-840c-4e32-ae69-99f5e327da04.png)

**Comment by yasudacloud** [comment]
@vojthor 
I see, thank you for the information.
I thought the error was in the callback, but I guess the problem is in the redirect.

I'll check to see if there is another way to implement the redirect.
Also, if you look at the response header when you open the page in the above capture, you might get a clue.
Is the URL not set correctly in the Location header?

**Comment by vojthor** [comment]
No need to apologize, you doing me huge favor in there :) I'm just keep messing it up more trying to debug it :D 
Will let you know but I believe it's issue on our side really somehow so you can close this issue :)

**Comment by vojthor** [comment]
@yasudacloud I messed the redirect by myself, it's totally fine, ignore that comment at all, sorry for that :)

**Comment by yasudacloud** [comment]
@vojthor 
I understand, and if you have any more questions, please don't hesitate to ask :D

Also, sorry for the confusing sentence. I used a translation tool because I don't speak English.
