### ISSUE TITLE
Request to /o/oauth2/token is triggered twice with same code

### ISSUE THREAD

**Issue by vojthor** [yasudacloud/strapi-plugin-sso#14]
Hey, it's me again :D So I guess I was able to identify the issue... from our logs it seems there is another call to `/o/oauth2/token` straight after the first one with the same code. And as the code was used it's no longer valid.
![image](https://user-images.githubusercontent.com/9679359/221533458-98d7bcd4-cf20-4b8e-aaf1-274f199fbfff.png)

(The first log is response from call to `/o/oauth2/token`, the second console is just `console.log(ctx.query);`inside `googleSignInCallback`)

**Comment by yasudacloud** [comment]
@vojthor 
It has been a while.

Thanks for the information.
Sorry for the personal reasons, but I am busy moving and would appreciate it if you could wait a few days. 
My apologies.

**Comment by yasudacloud** [comment]
@vojthor 
Sorry for the delay.
Regarding the above, do you have any idea why the callback URI is executed twice?

If the login was successful the first time, then the redirect should not be the cause.

**Comment by vojthor** [comment]
@yasudacloud Hey, no clue so far... it's just straight after that `/strapi-plugin-sso/google/callback...` is called it will fire `googleSignInCallback` function again. From logs I can see user is successfully authenticated after first call and the second one messing it up...

**Comment by yasudacloud** [comment]
@vojthor 
I thought it might be a webhook issue since it succeeded the first time, so I set up a webhook and deleted the Admin user once, but it did not reproduce.

If you don't mind, I would like to know the following?

1. The version of Strapi you are using
2. The version of strapi-plugin-sso
3. What is being done in the middleware (are there any other plug-ins interfering?)

**Comment by vojthor** [comment]
Thanks for looking into this :)
We using **Strapi v4.6.1**, **strapi-plugin-sso 0.1.5** (will try to deploy 0.1.6 now) and no middlewares that should interfere I'd say (we only using some changes to `strapi::security` because of S3 bucket for media upload)

**Comment by yasudacloud** [comment]
@vojthor 
`strapi::security` is a bit related.
 After the login is completed, the browser side I run JavaScript and have Content-Security-Policy set for security.

https://github.com/yasudacloud/strapi-plugin-sso/blob/main/server/controllers/google.js#L111

For example, if you override script-src like this, you would not be able to log in correctly.

```
  {
    name: 'strapi::security',
    config: {
      contentSecurityPolicy: {
        directives: {
          'script-src': [],
          'img-src': [],
        },
      }
    },
  },
```

**Comment by vojthor** [comment]
We using just those: 
``` 
  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          "connect-src": ["'self'", "https:"],
          "img-src": ["'self'", "data:", "blob:", env("AWS_CLOUDFRONT")],
          "media-src": ["'self'", "data:", "blob:", env("AWS_CLOUDFRONT")],
          upgradeInsecureRequests: null,
        },
      },
    },
  },
``` 
I would be more worried it if's for all users, but there is one guy out of like 20 so far :D It's really confusing where the issue should be, I'm not able to read anything from logs apart that second oAuth call

**Comment by yasudacloud** [comment]
@vojthor 
Okay, that may not be relevant.
I thought about it, but I don't think googleSignInCallback is being called twice.

I intentionally tried running it twice as shown below, but when the first login succeeds, it goes straight to the admin page.
```javascript
  this.googleSignInCallback(ctx)
```
