### ISSUE TITLE
[Question] Successfully redirected after login google, then not found error

### ISSUE THREAD

**Issue by untimated** [yasudacloud/strapi-plugin-sso#16]
Thank you for the plugin really appreciate it !

Just a little bit need of help here, about this response 
`{"data":null,"error":{"status":404,"name":"NotFoundError","message":"Not Found","details":{}}}`

I have checklisted google and its roles in the plugin admin, and have successfully redirected from google login (using unpublished app and external test users).

I probably missed something in the process, can you help point out where would that be?

**Comment by untimated** [comment]
hmm suddenly it works, must be because i logged in in other session with different user (without SSO) 

sry for the trouble

**Comment by yasudacloud** [comment]
@untimated 
Thank you for contacting us.

Sorry I could not get back to you sooner.
Please feel free to contact me again if you need anything else.
