### ISSUE TITLE
When you sign in successfully it redirects you to a hardcoded `/admin` url

### ISSUE THREAD

**Issue by joaquinodz** [yasudacloud/strapi-plugin-sso#18]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `strapi-plugin-sso@0.2.1` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/strapi-plugin-sso/server/services/oauth.js b/node_modules/strapi-plugin-sso/server/services/oauth.js
index 3a78f85..36490bc 100644
--- a/node_modules/strapi-plugin-sso/server/services/oauth.js
+++ b/node_modules/strapi-plugin-sso/server/services/oauth.js
@@ -77,7 +77,7 @@ module.exports = ({strapi}) => ({
  window.addEventListener('load', function() {
    sessionStorage.setItem('jwtToken', '"${jwtToken}"');
    sessionStorage.setItem('userInfo', '${JSON.stringify(user)}');
-   location.href = '/admin'
+   location.href = '${strapi.config.admin.url}'
  })
 </script>
 </head>
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by yasudacloud** [comment]
@joaquinodz 
I believe the problem has been resolved in v0.2.2, so I will close it.
Thanks! 🍺

https://github.com/yasudacloud/strapi-plugin-sso/pull/19
