### ISSUE TITLE
feature request: 'oidc implementation'   

### ISSUE THREAD

**Issue by minozheros** [yasudacloud/strapi-plugin-sso#26]
Hey, would it be possible to add a separate implementation for OIDC? It would work for authentik (https://github.com/yasudacloud/strapi-plugin-sso/issues/9) as well.

Regards Klaus

**Comment by yasudacloud** [comment]
@minozheros 
Hey, as long as we stay compatible and don't stray too far from the certification scope, we're good. Any cool ideas on your end?

**Comment by FlipperLP** [comment]
So Klaus was able to pull it off, we are cleaning the code, and going to make a PR. Because it is unlikely you have an Authentik instance, I can send you some OIDC-Details/-Credentials on Discord or in theory you could also use Google, but manually need to add the endpoints.
- Phil

**Comment by ChielTimmermans** [comment]
This is exactly what I need. Thank you guys for doing the work. 
Do you have a timeline on, when we can expect, a release?

**Comment by FlipperLP** [comment]
The code was working while we were testing it. We are just finalizing some things with the README documentation. Then we are just waiting for the repo owner to accept the PR request.

**Comment by yasudacloud** [comment]
@minozheros @FlipperLP @ChielTimmermans 
Thank you for your patience.
The version is 0.4.0.

Thank you for extending the functionality of the plugin.

**Comment by minozheros** [comment]
thank you. It was a pleasure working with you.
