### ISSUE TITLE
strapi version 4.15.1

### ISSUE THREAD

**Issue by fabriciomelosilva** [yasudacloud/strapi-plugin-sso#32]
In strapi version 4.15.1, we have the following error when starting the application with the plugin.

![Capturar](https://github.com/yasudacloud/strapi-plugin-sso/assets/6035579/1b8194ab-3c10-4865-a5c6-363c91d602a9)

**Comment by fabriciomelosilva** [comment]
I didn't install it this way. I put it as a dependency

  "dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^2.0.4",
    "@strapi/plugin-i18n": "4.14.6",
    "@strapi/plugin-users-permissions": "4.14.6",
    "@strapi/strapi": "4.14.6",
    "pg": "8.8.0",
    _**"strapi-plugin-sso": "^0.4.1"**_
    },
    
    
I run the commands:

yarn
yarn build
yarn develop

and the error happens when running the **yarn develop** command

**Comment by fabriciomelosilva** [comment]
The version 14.15.2 still has the same error.
There is also this step by step:

1. npx create-strapi-app@4.15.2 strapi_4_15_2
2. yarn add strapi-plugin-sso
3. yarn build
4. yarn develop

![image](https://github.com/yasudacloud/strapi-plugin-sso/assets/6035579/1707bf62-2669-4701-920c-9c15fa4f062c)

**Comment by felpsalvs** [comment]
Hello, I also came across the same problem as Fabrício

![image](https://github.com/yasudacloud/strapi-plugin-sso/assets/78622458/7cef6ef2-8dbd-4a84-b093-cfc9861b8dd9)

**Comment by yasudacloud** [comment]
@fabriciomelosilva @felpsalvs 
Thank you very much.
I have confirmed the error on my end.

Please wait a little while until it is fixed.

**Comment by fabriciomelosilva** [comment]
@yasudacloud thank you for your attention.

**Comment by yasudacloud** [comment]
I have released v0.4.2 and will close it.
Thank you!

**Comment by fabriciomelosilva** [comment]
thank you very much @yasudacloud
