### ISSUE TITLE
NotFound from @strapi/helper-plugin

### ISSUE THREAD

**Issue by adamrpostjr** [yasudacloud/strapi-plugin-sso#37]
export 'NotFound' (imported as 'NotFound') was not found in '@strapi/helper-plugin' (possible exports: AnErrorOccurred, AppInfoContext, AppInfoProvider, AppInfosContext, AppInfosProvider, AutoReloadOverlayBlockerContext, AutoReloadOverlayBlockerProvider, Body, CheckPagePermissions, CheckPermissions, ConfirmDialog, ContentBox, ContentManagerEditViewDataManagerContext, CustomFieldsContext, CustomFieldsProvider, DateTimePicker, DynamicTable, EmptyBodyTable, EmptyStateLayout, FilterListURLQuery, FilterPopoverURLQuery, Form, GenericInput, GuidedTourContext, GuidedTourProvider, InjectionZone, LibraryContext, LibraryProvider, Link, LinkButton, LoadingIndicatorPage, NoContent, NoMedia, NoPermissions, NotAllowedInput, NotificationsContext, NotificationsProvider, OverlayBlockerContext, OverlayBlockerProvider, PageSizeURLQuery, PaginationURLQuery, RBACContext, RBACProviderContext, ReactSelect, RelativeTime, RemoveRoundedButton, Root, SearchURLQuery, SettingsPageTitle, SortIcon, Status, StopPropagation, StrapiAppContext, StrapiAppProvider, Table, TrackingContext, TrackingProvider, auth, contentManagementUtilRemoveFieldsFromData, difference, findMatchingPermissions, formatContentTypeData, formatPermissionsForRequest, getAPIInnerErrors, getFetchClient, getFileExtension, getOtherInfos, getType, getYupInnerErrors, hasPermissions, normalizeAPIError, onRowClick, prefixFileUrlWithBackendUrl, prefixPluginTranslations, pxToRem, request, setHexOpacity, shouldCheckPermissions, stopPropagation, to, translatedErrors, useAPIErrorHandler, useAppInfo, useAppInfos, useAutoReloadOverlayBlocker, useCMEditViewDataManager, useCallbackRef, useClipboard, useCollator, useCustomFields, useFetchClient, useFilter, useFocusInputField, useFocusWhenNavigate, useGuidedTour, useLibrary, useLockScroll, useNotification, useOverlayBlocker, usePersistentState, useQuery, useQueryParams, useRBAC, useRBACProvider, useSelectionState, useStrapiApp, useTableContext, useTracking, wrapAxiosInstance)

**Comment by yasudacloud** [comment]
@adamrpostjr 
Sorry, I will check.

I would like to know what version of Strapi you have.

**Comment by adamrpostjr** [comment]
Sure!
"@strapi/strapi": "4.16.2",

**Comment by yasudacloud** [comment]
@adamrpostjr 
Sorry for the delay. 
The above error was not reproduced in my local environment.
However, from what I have seen of the error, I think I can work around it and will fix it by next Monday.
Please wait a little longer.

**Comment by yasudacloud** [comment]
@adamrpostjr 
Version 0.4.3 is now available.
This change removes references to NotFound components, so the error probably no longer occurs.

It would be helpful if you could check the operation when you have time.

**Comment by adamrpostjr** [comment]
Seems to be fine for me!
Thank you!
