### ISSUE TITLE
Issue with triggerWebHook function

### ISSUE THREAD

**Issue by PhuocMinhcs** [yasudacloud/strapi-plugin-sso#45]
I got the issue after login with Azure AD

![Untitled](https://github.com/yasudacloud/strapi-plugin-sso/assets/25609082/1741406e-db46-4eb1-87fd-68af9b4c47fb)
And I found the root cause related to this function **_triggerWebHook_** at strapi-plugin-sso\server\services\oauth.js line 57

`const {ENTRY_CREATE} = strapi.webhookStore.allowedEvents;`

the _strapi.webhookStore.allowedEvents_ return _undefined_

Suggestion: using the event name '_entry.create_' instead like this at line 60

`strapi.eventHub.emit('entry.create' /*ENTRY_CREATE*/, {
      model: modelDef.modelName,
      entry: sanitizedEntity,
    });`
    
My Strapi version:  **_"@strapi/strapi": "4.10.5"_**

**Comment by yasudacloud** [comment]
@PhuocMinhcs 
Thanks for the report.
Please wait as we investigate.

**Comment by yasudacloud** [comment]
@PhuocMinhcs 
Sorry for the delay, we fixed this issue in version 0.4.4.
Please contact us if you have any further questions.

**Comment by PhuocMinhcs** [comment]
@yasudacloud Nice, thank you for your notice!
