### ISSUE TITLE
No plugin homepage link or route

### ISSUE THREAD

**Issue by giuliogatto** [yasudacloud/strapi-plugin-sso#49]
I am logged as ad administrator but I cannot get either the link or the route for the admin plugin page:
<img width="691" alt="Screenshot 2024-02-05 at 10 59 03" src="https://github.com/yasudacloud/strapi-plugin-sso/assets/11378447/2d453059-b89e-4d90-96e0-3a17da01e3ba">

The plugin is otherwise working and successfully loggin in by visiting the url /strapi-plugin-sso/azuread

Am I missing something?
Thanks

**Comment by yasudacloud** [comment]
@giuliogatto 
This is the first time I've encountered this issue.
I assume it should appear if the user's role is set as Super Admin.
If you could let us know the versions of Strapi and the plugin, we might be able to investigate this a bit further.

By the way, my local environment is like this
<img width="1249" alt="スクリーンショット 2024-02-05 22 31 42" src="https://github.com/yasudacloud/strapi-plugin-sso/assets/44352732/d6f8b564-1964-4276-950f-8526e683d312">

**Comment by giuliogatto** [comment]
@yasudacloud thank you for your quick reply.
I am using Strapi "4.13.6" and I also have another plugin that I wrote (it's called Build website you can see in the screenshot above). I suspect this issue is either related to my Strapi version or to a conflict with my plugin.. I am trying to investigate and debug the code

**Comment by yasudacloud** [comment]
@giuliogatto 
Thanks for the information.
I have installed v4.13.6 and it seems to be working correctly.

If I could solve the problem any other way...)
1. try disabling the other one's plugin.
2. stop the process once and run `yarn build && yarn start` again

**Comment by giuliogatto** [comment]
OK, I am debugging the code to find the culprit. Thank you for your assistance, I will let you know if i find something

**Comment by giuliogatto** [comment]
Ok, rebuilding everything from scratch, after removing all other plugins, solved the issue
