### ISSUE TITLE
Change Admin url to use only SSO

### ISSUE THREAD

**Issue by Xora123** [yasudacloud/strapi-plugin-sso#53]
Hey , there is an configuration in your plugin to only use the sso url like (strapi-plugin-sso/azurad) ? instead of using admin/auth/login ?

**Comment by yasudacloud** [comment]
@Xora123 
Thanks for posting!

There is no function in the plugin to disable admin/auth/login.
How about placing a web server in front of Strapi and redirecting the admin/auth/login path?

**Comment by Xora123** [comment]
Thanks you for taking time to reply! 

Ok, maybe that's the solution, thank you.
